-- Upsert 27 adventure missions (fixed UUIDs). Deactivate legacy adventure seed row.
-- Source: docs/missions.seed.json

insert into public.missions (id, category, teaser, title, body, locale, is_active)
values
  ('a1f2e3d4-c5b6-4789-a012-345678040001'::uuid, 'adventure'::public.mission_category, 'There''s a street you always ignore.', 'Mission: the unfamiliar turn', 'The next time you head somewhere nearby, take one street, path, or lane you normally ignore. Follow it for a few minutes and notice what changes. Turn back whenever you like. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040002'::uuid, 'adventure'::public.mission_category, 'Efficiency can wait one block.', 'Mission: route detour', 'While walking, add a small loop to your usual route. Stay curious instead of efficient. Stop after one extra block, bend, or stretch of road.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040003'::uuid, 'adventure'::public.mission_category, 'Same place. Different entrance.', 'Mission: new doorway', 'Visit a familiar place and enter from a different side or approach if possible. Notice what catches your attention first. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040004'::uuid, 'adventure'::public.mission_category, 'Left, right, or straight — then go.', 'Mission: follow a direction', 'Step outside or to a window. Choose left, right, or straight without overthinking it, then explore that direction for five minutes. Head back whenever you''re ready.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040005'::uuid, 'adventure'::public.mission_category, 'Something in the distance is worth reaching.', 'Mission: chase a landmark', 'Spot something in the distance—a tree, roofline, fence, hill, or sign. Move toward it if it''s safely reachable nearby. Once you arrive, you''re done.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040006'::uuid, 'adventure'::public.mission_category, 'Walk half as fast for three minutes.', 'Mission: slower than usual', 'Walk more slowly than you normally would for three minutes. Let details appear that usually blur past. Return to your normal pace after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040007'::uuid, 'adventure'::public.mission_category, 'Stand somewhere you never choose.', 'Mission: new vantage point', 'Find a spot nearby where you don''t usually stand—another corner of a yard, a different bench, the far side of a room. Stay there for two minutes and take in the scene. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040009'::uuid, 'adventure'::public.mission_category, 'See a familiar place at an unusual hour.', 'Mission: different timing', 'Visit a nearby spot you know well at a time you don''t usually see it. Notice how the light, sounds, or activity differ. Stay only a few minutes.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040010'::uuid, 'adventure'::public.mission_category, 'No destination — only what pulls you.', 'Mission: follow curiosity', 'Start moving with no destination beyond your immediate area. When something genuinely catches your attention, go closer and examine it for a minute. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040011'::uuid, 'adventure'::public.mission_category, 'Your everyday room still has surprises.', 'Mission: indoor expedition', 'Choose a room you use every day. Spend five minutes noticing corners, shelves, or objects you''ve stopped seeing. End when you''ve found three surprises.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040012'::uuid, 'adventure'::public.mission_category, 'Ten minutes with nowhere to be.', 'Mission: no destination', 'Head outside or into a shared space without a plan. Let each small decision come from whatever interests you next. Stop after ten minutes.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040013'::uuid, 'adventure'::public.mission_category, 'Find something older than everything else.', 'Mission: time traveler', 'Look around your surroundings and search for something that seems older than everything else nearby. Spend a moment imagining what it has witnessed. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040014'::uuid, 'adventure'::public.mission_category, 'Ask the place what''s most interesting.', 'Mission: ask the place', 'Wherever you are, ask yourself: ''What''s the most interesting thing here?'' Go investigate your answer. Stop after a few minutes.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040015'::uuid, 'adventure'::public.mission_category, 'Step from one world into another nearby.', 'Mission: cross over', 'Move from one environment into another nearby: indoors to outdoors, pavement to grass, busy to quiet, sun to shade. Notice the shift. Stay with it for a minute.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040017'::uuid, 'adventure'::public.mission_category, 'Take the long way on purpose.', 'Mission: scenic version', 'Choose the less direct option for a short trip nearby. Pay attention to what appears because you weren''t rushing. Return to normal after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040018'::uuid, 'adventure'::public.mission_category, 'Wander until somewhere makes you stop.', 'Mission: pause point', 'Wander until you find a spot that makes you want to stop for thirty seconds. Stand there and take in the surroundings. Then continue or head home.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040019'::uuid, 'adventure'::public.mission_category, 'Walk to the edge of your usual map.', 'Mission: edge of familiar', 'Go to the furthest point nearby that still feels part of your everyday territory. Spend two minutes there. Turn back after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040020'::uuid, 'adventure'::public.mission_category, 'Somewhere you haven''t been in a while.', 'Mission: revisit briefly', 'Return to a place you haven''t visited in a while but can reach easily. Compare it with your memory. Stay only a few minutes.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040021'::uuid, 'adventure'::public.mission_category, 'Follow a sound until you''ve found it.', 'Mission: sound trail', 'Notice a distant sound—a bird, machinery, voices, wind, or water. Move toward it if practical and safe. Stop when you''ve located the source or satisfied your curiosity.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040022'::uuid, 'adventure'::public.mission_category, 'Change your height for a new view.', 'Mission: higher or lower', 'Find a nearby spot slightly higher or lower than where you are now. Spend a moment observing from that new perspective. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040024'::uuid, 'adventure'::public.mission_category, 'Inspect something you always pass.', 'Mission: object expedition', 'Choose one object you pass often outdoors or in a shared space. Walk over and inspect it more closely than usual. End once you''ve noticed three details.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040025'::uuid, 'adventure'::public.mission_category, 'Sit where you never sit.', 'Mission: different seat', 'Sit somewhere you don''t normally choose—a different chair, bench, step, or patch of ground. Stay for three minutes and watch the world from there. Then move on.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040026'::uuid, 'adventure'::public.mission_category, 'Find a bend and see what''s past it.', 'Mission: follow the curve', 'Seek out a winding path, road, hallway, or trail nearby. Follow it until the next bend or turn. Stop after seeing what''s around it.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040027'::uuid, 'adventure'::public.mission_category, 'Match someone''s walking rhythm for one minute.', 'Mission: match the rhythm', 'Observe the pace of someone walking nearby, or imagine one if you''re alone. Match that rhythm for one minute. Return to your own pace after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040028'::uuid, 'adventure'::public.mission_category, 'Pick the smallest visible target.', 'Mission: tiny destination', 'Choose something small you can see nearby—a flower, mailbox, stone, post, or gate. Make it your destination. Once you reach it, you''re done.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040029'::uuid, 'adventure'::public.mission_category, 'Two minutes inside one square meter.', 'Mission: one-square-meter safari', 'Focus on a very small area around you, indoors or outdoors. Search it as if you''re seeing it for the first time. Stop after two minutes.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678040030'::uuid, 'adventure'::public.mission_category, 'Close the gap on something you''ve only seen from afar.', 'Mission: close the distance', 'Notice something you''ve only ever seen from afar in your area. Walk closer and examine it for a minute. That''s enough for today.', 'en', true)
on conflict (id) do update set
  category = excluded.category,
  teaser = excluded.teaser,
  title = excluded.title,
  body = excluded.body,
  locale = excluded.locale,
  is_active = excluded.is_active;

update public.missions
set is_active = false
where id in (
  'a1f2e3d4-c5b6-4789-a012-345678901107'::uuid
);
