-- Generated by scripts/generate-mission-seed.mjs — source: docs/missions.seed.json
insert into public.missions (id, category, teaser, title, body, locale, is_active)
values
  ('a1f2e3d4-c5b6-4789-a012-345678901101'::uuid, 'social'::public.mission_category, 'Someone might love hearing from you today.', 'Mission: reach out', 'Think of one person you genuinely miss. Send them a short message — not a meme, not a link. Just you, checking in.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901102'::uuid, 'social'::public.mission_category, 'Your voice counts more than a tap.', 'Mission: use your voice', 'Call someone you usually only text. It can be two minutes. Ask how they are and really listen.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901103'::uuid, 'nature'::public.mission_category, '30 seconds. No goal. Just look.', 'Mission: notice the outside', 'Go to a window or step outside for 30 seconds. Name one thing you never really noticed before — a sound, a shape, a color.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901104'::uuid, 'nature'::public.mission_category, 'Touch something alive.', 'Mission: connect with the living world', 'Find a plant, a tree, grass, or a pet. Touch it gently. Take one slow breath while you do.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901105'::uuid, 'curiosity'::public.mission_category, 'One question you’ve never asked.', 'Mission: ask something new', 'Ask someone a real question you’ve never asked them before — about their day, a memory, or what they’re excited about. Stay curious, not clever.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901106'::uuid, 'curiosity'::public.mission_category, 'Learn one small thing offline.', 'Mission: a tiny discovery', 'Learn one new fact without opening a feed — read a page of a book, a sign on the street, or ask a human. One fact. That’s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901107'::uuid, 'adventure'::public.mission_category, 'Change the route. Change the day.', 'Mission: take a different path', 'On your next walk or commute, take one different turn — even a small one. Pay attention to what’s different.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901108'::uuid, 'creativity'::public.mission_category, 'Make something small, just for you.', 'Mission: a 5-minute creation', 'For five minutes, make something with your hands — doodle, fold paper, hum a melody, rearrange a corner of your space. No posting required.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901109'::uuid, 'calm'::public.mission_category, 'Silence is not empty.', 'Mission: give your brain quiet', 'Sit or stand still for two minutes without a podcast, video, or feed. Hear the room. Let your mind drift without grabbing new input.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678901110'::uuid, 'learning'::public.mission_category, 'One skill, tiny step.', 'Mission: micro-practice', 'Pick something you’ve wanted to learn. Do exactly one tiny practice — one chord, one sentence, one stretch, one line read aloud. Stop after that one step.', 'en', true)
on conflict (id) do update set
  category = excluded.category,
  teaser = excluded.teaser,
  title = excluded.title,
  body = excluded.body,
  locale = excluded.locale,
  is_active = excluded.is_active;
