-- Upsert 33 social missions (fixed UUIDs). Deactivate legacy social seed rows.
-- Source: docs/missions.seed.json

insert into public.missions (id, category, teaser, title, body, locale, is_active)
values
  ('a1f2e3d4-c5b6-4789-a012-345678010001'::uuid, 'social'::public.mission_category, 'There''s someone you only react to. Try words instead.', 'Mission: say something real', 'Open a chat with someone you usually only send emojis or likes to. Write one honest sentence about your day or theirs. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010003'::uuid, 'social'::public.mission_category, 'Someone in your contacts deserves a voice note.', 'Mission: send your voice', 'Record a short voice message for one person you trust. Keep it simple: a memory, a thank you, or a quick hello. You do not need to continue the conversation.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010004'::uuid, 'social'::public.mission_category, 'A familiar face is waiting for recognition.', 'Mission: acknowledge someone', 'Make eye contact with someone you see often but rarely speak to — a neighbor, cashier, receptionist, or barista. Say hello like you mean it. Stop there if you want.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010005'::uuid, 'social'::public.mission_category, 'Ask a question with no practical purpose.', 'Mission: ask something human', 'During your next conversation, ask someone what they''ve been enjoying lately. Don''t turn it into advice or recommendations. Just stay curious for two minutes.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010006'::uuid, 'social'::public.mission_category, 'A compliment is sitting unsent.', 'Mission: say the nice thing', 'Think of one specific thing you appreciate about someone. Tell them directly in one sentence. No extra explanation needed.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010008'::uuid, 'social'::public.mission_category, 'Call someone without needing anything.', 'Mission: unexpected call', 'Phone one person you usually only text. Keep the call under five minutes if you want. The point is hearing a voice.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010009'::uuid, 'social'::public.mission_category, 'There''s a tiny favor you can offer.', 'Mission: make life lighter', 'Ask someone nearby if they need help carrying, moving, or reaching something small. Accept yes or no without insisting. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010010'::uuid, 'social'::public.mission_category, 'One message can reopen a quiet friendship.', 'Mission: reopen the thread', 'Send a short message to someone you haven''t spoken to in months. Mention a memory or ask how they''ve been lately. You don''t need to explain the silence.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010012'::uuid, 'social'::public.mission_category, 'Your future self might remember this stranger.', 'Mission: ask for a recommendation', 'Ask someone nearby for a recommendation — a bakery item, a park, a movie, anything local and simple. Thank them and move on. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010013'::uuid, 'social'::public.mission_category, 'Sit closer to people today.', 'Mission: choose proximity', 'In a public place, sit near other people instead of automatically choosing the isolated corner. Stay present for a few minutes. No conversation required.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010014'::uuid, 'social'::public.mission_category, 'There''s a thank-you you forgot to send.', 'Mission: close the loop', 'Message someone who helped you recently, even in a small way. Be specific about what you appreciated. Stop after sending it.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010015'::uuid, 'social'::public.mission_category, 'Share a memory instead of an update.', 'Mission: bring something back', 'Text someone a memory you still laugh about or think about sometimes. Don''t add a photo or link. Just the moment itself.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010016'::uuid, 'social'::public.mission_category, 'You can make someone feel noticed in 10 seconds.', 'Mission: use their name', 'During your next interaction, say the person''s name out loud once if you know it. Keep the rest natural. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010017'::uuid, 'social'::public.mission_category, 'A tiny invitation counts.', 'Mission: ask someone along', 'Invite someone to join you for a very small thing today — a coffee run, short walk, or quick errand. Keep it low pressure. One ask is enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010018'::uuid, 'social'::public.mission_category, 'Be the first person to wave.', 'Mission: start the hello', 'When you pass someone familiar today, greet them before they greet you. Keep walking if you want afterward. Stop there.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010019'::uuid, 'social'::public.mission_category, 'One honest answer could change the tone.', 'Mission: answer properly', 'The next time someone asks how you are, answer with one real sentence instead of autopilot. Nothing dramatic required. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010021'::uuid, 'social'::public.mission_category, 'Someone around you has a story you''ll never hear.', 'Mission: small curiosity', 'Ask a simple follow-up question during a casual interaction today. Stay with the answer instead of turning back to yourself immediately. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010022'::uuid, 'social'::public.mission_category, 'An old friend might answer faster than you think.', 'Mission: random check-in', 'Choose one person you haven''t thought about in a while. Send a short message asking what life has been like lately. Stop after pressing send.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010024'::uuid, 'social'::public.mission_category, 'You don''t need a reason to reach out.', 'Mission: send the first text', 'Start a conversation today without needing news, plans, or logistics. A simple "thought of you" is enough. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010025'::uuid, 'social'::public.mission_category, 'Notice who always initiates with you.', 'Mission: reverse the pattern', 'Think of someone who usually reaches out first. Contact them before they contact you this time. Keep it short and easy.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010032'::uuid, 'social'::public.mission_category, 'You already know more neighbors than you think.', 'Mission: hallway hello', 'If you cross paths with a neighbor today, pause for one extra sentence instead of a quick nod. Keep it casual and brief. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010033'::uuid, 'social'::public.mission_category, 'One person deserves your full attention for 2 minutes.', 'Mission: listen without fixing', 'During one conversation today, resist giving advice or turning the topic back to yourself. Just listen until the other person finishes. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010035'::uuid, 'social'::public.mission_category, 'A real laugh sounds better out loud.', 'Mission: share something funny', 'Tell someone about a genuinely funny thing that happened recently instead of sending a clip or meme. Keep it imperfect. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010036'::uuid, 'social'::public.mission_category, 'Notice who makes your days easier.', 'Mission: appreciate the regulars', 'Thank someone whose work quietly supports your routine — cleaner, driver, receptionist, cashier, delivery worker. Keep it direct and simple. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010037'::uuid, 'social'::public.mission_category, 'A question can change a whole mood.', 'Mission: ask about today', 'Ask someone what the best part of their day has been so far. Listen to the first answer without rushing onward. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010039'::uuid, 'social'::public.mission_category, 'There''s probably a local regular you recognize.', 'Mission: become familiar', 'Return to a place you visit sometimes and stay long enough for one brief interaction with the people there. Recognition counts. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010040'::uuid, 'social'::public.mission_category, 'Try one tiny act of trust.', 'Mission: ask for help', 'Ask someone for a small favor today — directions, an opinion, help opening something, a recommendation. Let them help if they want to. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010042'::uuid, 'social'::public.mission_category, 'Someone in your life needs encouragement.', 'Mission: back someone up', 'Send a message reminding someone that they''re doing better than they think at something specific. Keep it grounded and short. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010043'::uuid, 'social'::public.mission_category, 'You can change the energy of a room quietly.', 'Mission: arrive open', 'When entering a shared space today, look up instead of immediately disappearing into your own world. A smile or nod is enough. Stop there.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010044'::uuid, 'social'::public.mission_category, 'Reconnect through a shared memory.', 'Mission: remember together', 'Message someone about a place, song, meal, or moment you both experienced. Let the memory sit without forcing a long conversation. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010046'::uuid, 'social'::public.mission_category, 'Someone would probably answer if you invited them.', 'Mission: make a simple plan', 'Invite one person to do something low-effort this week — coffee, lunch, a walk, browsing a shop. Keep the invitation casual. That''s enough.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010047'::uuid, 'social'::public.mission_category, 'Try noticing the quiet people.', 'Mission: include someone', 'During a group moment today, direct one question toward the quieter person in the room. Give them space to answer. Stop after that.', 'en', true),
  ('a1f2e3d4-c5b6-4789-a012-345678010049'::uuid, 'social'::public.mission_category, 'Your attention is useful to someone.', 'Mission: notice effort', 'Tell someone you noticed a specific effort they made recently — cooking, organizing, showing up, helping, trying. Keep it sincere and brief. Stop after that.', 'en', true)
on conflict (id) do update set
  category = excluded.category,
  teaser = excluded.teaser,
  title = excluded.title,
  body = excluded.body,
  locale = excluded.locale,
  is_active = excluded.is_active;

update public.missions
set is_active = false
where id in (
  'a1f2e3d4-c5b6-4789-a012-345678901101'::uuid,
  'a1f2e3d4-c5b6-4789-a012-345678901102'::uuid
);
